### PR TITLE
Generate and upload AppImage, closes #10

### LINKED ISSUE #10: Setup Travis-CI for build AppImage
Cast @probonopd

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
Argh, why are there changes all over the place now? Should I have sent the PR against another branch?

**Comment by tomlechner** [comment]
Was this after merging changes from master? I don't think I did anything super drastic, I'd have expected it to merge cleanly.
master is the branch under active development, which I've been working on a lot. release is the "stable" branch. It would be nice to have it on master though, since I tend to go maybe too long between releases.

**Comment by probonopd** [comment]
I am not a git wizard, not sure what I did wrong.

**Comment by tomlechner** [comment]
I lean a lot on my git cheat sheet that I've slowly accumulated..

Those files definitely look like older versions. To merge from Laidout's original master, to make sure your branch is up to date before a pull request, according to my cheat sheet, it goes like this:

1. make your local git repo know about a new remote source:
```
git remote add LaidoutUpstream https://github.com/Laidout/laidout
git fetch LaidoutUpstream
```
2. Merge (this way skips an extra commit message):
```
git pull --rebase LaidoutUpstream master
```

At this point, if all is well your forked repo should be up to date with the Laidout master branch, and the pull request shouldn't complain. At least not about the same things.

If something goes wrong, is it just the .travis.yml and AppRun files that are new? I can add those manually I suppose. In general I wouldn't want packaging specific files randomly laying around in the top level directory, they would get their own subdirectory where I can put a packaging specific readme with it, but if it's just AppRun and one hidden dot file, I could live with that.

**Comment by probonopd** [comment]
>  If something goes wrong, is it just the .travis.yml and AppRun files that are new? I can add those manually I suppose. In general I wouldn't want packaging specific files randomly laying around in the top level directory, they would get their own subdirectory where I can put a packaging specific readme with it, but if it's just AppRun and one hidden dot file, I could live with that.

Yes, I think this may be the easiest route.

**Comment by tomlechner** [comment]
Ok, added files manually and finally had some time to learn travis a little.
The build seems to be working! Let me know if you spot anything off!
Thanks for your work on this. I'd like to announce on Laidout's website and add you to Laidout's contributor list if that's ok. Is "probonopd" sufficient, or should I use your name? Feel free to email if you have special concerns about attribution.

https://github.com/Laidout/laidout/releases/tag/continuous

**Pull request closed without merging**
